/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rmolabanti' at '11/6/17 9:22 PM' with Gradle 2.6
 *
 * @author rmolabanti, @date 11/6/17 9:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
